ktor:
  application:
    modules:
      - com.studentify.ApplicationKt.module
  deployment:
    port: 8080
    host: 0.0.0.0

jwt:
  domain: "https://studentify.edu"
  audience: "studentify-app"
  realm: "Studentify API"
  secret: "your_strong_secret_here"

postgres:
  url: "jdbc:postgresql://localhost:5432/studentify"
  user: "postgres"
  password: "0852"