# ngrok http --url=modern-marmot-eminently.ngrok-free.app 8081

ktor:
  application:
    modules:
      - com.studentify.ApplicationKt.module
  deployment:
    port: 8081
    host: 0.0.0.0

jwt:
  secret: "your_very_strong_secret_here_at_least_32_chars"
  issuer: "studentify-server"
  audience: "studentify-app"
  realm: "Studentify API"

postgres:
  url: "jdbc:postgresql://localhost:5432/studentify"
  user: "postgres"
  password: "0852"